<?php
class Step extends SetupStep {
  public function execute() {
    $this->createTagzTables();
    Setup::finish();
  }
  
  protected function createTagzTables() {
    $query_objects = "CREATE TABLE `objects` (                                                                                
             `objectId` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Autogenerated unique id for an object',  
             `object` text NOT NULL COMMENT 'the object representation',                                           
             `typeId` bigint(20) NOT NULL COMMENT 'Tag Id that indicates the type of the object',                  
             `createdOn` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,                                             
             `uid` varchar(20) NOT NULL COMMENT 'The associated user of the object',                               
             PRIMARY KEY (`objectId`)                                                                              
           ) ENGINE=MyISAM AUTO_INCREMENT=93 DEFAULT CHARSET=utf8 COMMENT='Table that holds all objects.' ;";
    
    $query_objectIndex = "CREATE TABLE `objectIndex` (                    
                 `objectId` int(11) NOT NULL,                  
                 `property` tinytext NOT NULL,                 
                 `value` text NOT NULL,                        
                 FULLTEXT KEY `property` (`property`,`value`)  
               ) ENGINE=MyISAM DEFAULT CHARSET=utf8;";
               
    $query = $query_objects.$query_objectIndex;
    DB::execQuery($query, true);
  }
}

?>


